# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# 웹페이지 언어 설정 (한국어인 ko로 변경)
lang: ko

# 타임존 설정 (한국 시간으로 변경)
timezone: Asia/Seoul

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: 'infra&DevOps' # 블로그 대문 메인 제목

tagline: '주니어 DevOps의 인프라 및 기술 기록' # 사이드바에 들어갈 블로그 한 줄 소개

description: >- # 구글 검색 등에 노출될 블로그 설명
  인프라 엔지니어링 성장 과정을 담은 기술 블로그입니다.

# 본인의 GitHub Pages 주소 설정 (MsLJ에 맞춤)
url: "https://MsLJ.github.io"

github:
  username: MsLJ # GitHub 유저네임

twitter:
  username: # 트위터 안 쓰시면 비워두셔도 됩니다.

social:
  # 하단 푸터에 표시될 저작권자 이름
  name: MsLJ
  email: # 필요 시 이메일 주소를 적으세요 (예: example@domain.com)
  fediverse_handle: 
  links:
    # 사이드바 하단 소셜 아이콘 링크 설정
    - https://github.com/MsLJ # 내 깃허브 홈피 주소
    # 추가하고 싶은 링크가 있다면 아래 주석(#)을 풀고 적으시면 됩니다.
    # - https://www.linkedin.com/in/username

# Site Verification Settings
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
  facebook: 

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
analytics:
  google:
    id: 
  goatcounter:
    id: 
  umami:
    id: 
    domain: 
  matomo:
    id: 
    domain: 
  cloudflare:
    id: 
  fathom:
    id: 

# Page views settings
pageviews:
  provider: 

# 선호하는 테마 모드 설정 (비워두면 시스템 설정을 따르며 사이드바 하단에서 다크/라이트 모드 수동 전환 가능)
theme_mode: 

# 메디아 자원 CDN 경로 (기본값 비워둠)
cdn:

# 사이드바 프로필 아바타 이미지 (나중에 이미지 올린 후 경로 지정 가능)
avatar:

# SEO용 소셜 미리보기 이미지
social_preview_image: 

# 포스팅 내 목차(TOC) 사용 여부
toc: true

comments:
  # 댓글 시스템 활성화 (giscus 지정)
  provider: giscus

  # Giscus 세부 설정
  giscus:
    repo: MsLJ/MsLJ.github.io          # <내유저네임>/<저장소이름>
    repo_id:                   # (※ 일단 비워두거나 아래 팁을 확인하세요)
    category: Announcements            # 댓글이 생성될 깃허브 카테고리 지정
    category_id:              # (※ 일단 비워두거나 아래 팁을 확인하세요)
    mapping: pathname
    strict: '0'
    input_position: bottom
    lang: ko                           # 댓글창 언어를 한국어로 설정
    reactions_enabled: '1'             # 이모지 좋아요 기능 활성화

# 자가 호스팅 정적 자산 설정
assets:
  self_host:
    enabled: 
    env: 

pwa:
  enabled: true # PWA 기능 활성화 (앱처럼 설치 가능)
  cache:
    enabled: true 
    deny_paths:

paginate: 10

# 기본 서브 경로 (사용하지 않으므로 비워둠)
baseurl: ""

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" 
      type: posts
    values:
      layout: post
      comments: true 
      toc: true 
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs 
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
